version: "3.9"
name: adsb-dev

services:
  redis:
    image: redis:7
    ports: ["6379:6379"]

  collector:
    build: ./collector
    env_file: .env
    depends_on: [redis]
    volumes:
      - ./data:/data
#  uploader:
 #   build: ./uploader
  #  env_file: .env
   # depends_on: [redis]
